# Change baseurl before deploy
baseurl = "https://blog.ltlyl.fun/"
languageCode = "zh-cn"
title = "ltlyl"

# GA Tracking ID
googleAnalytics = "G-8LR72PVL5E"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true



[pagination]
pagerSize = 5